<a href="https://colab.research.google.com/github/deltania/Orbit_Academy/blob/main/Numpy_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

# Creating Arrays

In [1]:
# Import Library NumPy
import numpy as np

# Contoh Membuat Array
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [2]:
# Menampilkan Array a
a

array([1, 2, 3])

In [3]:
# Menampilkan Array b
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
# Menampilkan Array c
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [6]:
d

NameError: ignored

### Initial Placeholders

In [ ]:
# Create an array of zeros
np.zeros((2,3,2))

In [ ]:
# Create an array of ones
np.ones((2,3,4),dtype=np.int16)

In [ ]:
np.eye(3,3)

In [ ]:
# Create an array of evenly spaced values (step value)
d = np.arange(10,100,10)
d

In [ ]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0,3,9)

In [ ]:
# Create a constant array
e = np.full((2,2),7)
e

In [ ]:
# Create a 2X2 identity matrix
f = np.eye(2)
f

In [ ]:
# Create an array with random values
np.random.random((2,2))

In [ ]:
# Create an empty array
np.empty((3,2))

# Input Output

### Saving & Loading On Disk

In [ ]:
# np.save('my_array', a)
# np.savez('array.npz', a, b)
# np.load('my_array.npy')

In [ ]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

# Data Types

In [ ]:
# Signed 64-bit integer types
np.int64

In [ ]:
# Standard double-precision floating point
np.float32

In [ ]:
# Complex numbers represented by 128 floats
np.complex

In [ ]:
# Boolean type storing TRUE and FALSE values
np.bool

In [ ]:
# Python object type
np.object

In [ ]:
# Fixed-length string type
np.string_

In [ ]:
# Fixed-length unicode type
np.unicode_

# Inspecting Your Array 

In [ ]:
# Array dimensions
a.shape

In [ ]:
# Length of array
len(a)

In [ ]:
# Number of array dimensions
b.ndim

In [ ]:
# Number of array elements
e.size

In [ ]:
# Data type of array elements
b.dtype

In [ ]:
# Name of data type
b.dtype.name

In [ ]:
# Convert an array to a different type
b.astype(int)

# Array Mathematics
## Arithmetic Operations

### Subtraction

In [ ]:
# Pengurangan Array - a-b
g = a - b
g

In [ ]:
# Pengurangan Array - a-b
np.subtract(a,b)

### Addition

In [ ]:
# Penjumlahan Array - b+a
b + a

In [ ]:
# Penjumlahan Array - b+a
np.add(b,a)

### Division

In [ ]:
# Pembagian Array - a/b
a / b

In [ ]:
# Pembagian Array - a/b
np.divide(a,b)

### Multiplication

In [ ]:
# Perkalian Array - a*b
a * b

In [ ]:
# Perkalian Array - a*b
np.multiply(a,b)

### Exponentiation

In [ ]:
# Fungsi eksponensial pada array b
np.exp(b)

### Square root

In [ ]:
# Fungsi akar pada array b
np.sqrt(b)

### Print sines of an array

In [ ]:
# Nilai Sinus pada array a
np.sin(a)

### Element-wise cosine 

In [ ]:
# Nilai Cosinus pada array b
np.cos(b)

### Element-wise natural logarithm

In [ ]:
# Nilai logaritma pada array a
np.log(a)

### Dot product

In [ ]:
# Perkalian Titik pada array f
e.dot(f)

## Comparison

### Element-wise comparison

In [ ]:
# Perbandingan elemen array a==b 
a == b

In [ ]:
# Perbandingan elemen array a<2
a < 2

### Array-wise comparison

In [ ]:
# Perbandingan array a,b
np.array_equal(a, b)

## Aggregate Functions

### Array-wise sum

In [ ]:
# Agregasi nilai total array a
a.sum()

### Array-wise minimum value

In [ ]:
# Agregasi nilai minimal array a
a.min()

### Maximum value of an array row

In [ ]:
# Agregasi nilai maksimal array b
b.max(axis=0)

### Cumulative sum of the elements

In [ ]:
# Nilai kumulatif pada array b
b.cumsum(axis=1)

### Mean

In [ ]:
# Nilai Mean array a
a.mean()

### Median 

In [ ]:
# Nilai Median array b
np.median(b)

### Correlation coefficient

In [ ]:
# Nilai korelasi koefisien array a
np.corrcoef(a)

### Standard deviation

In [ ]:
# Nilai standar defiasi array b
np.std(b)

# Copying Arrays

### Create a view of the array with the same data

In [ ]:
# Melihat isi array a
h = a.view()
h

### Create a copy of the array

In [ ]:
# Copy array a
np.copy(a)

### Create a deep copy of the array

In [ ]:
# Deef copy array a
h = a.copy()
h

# Sorting Arrays

### Sort an array

In [ ]:
# Mengurutkan array a
a.sort()
a

### Sort the elements of an array's axis

In [ ]:
# Mengurutkan array c
c.sort(axis=0)
c

# Subsetting, Slicing, Indexing

## Subsetting

### Select the element at the 2nd index

In [ ]:
# Mengambil nilai index ke 2 pada elemen array a
a[2]

### Select the element at row 1 column 2 (equivalent to b[1][2])


In [ ]:
# Mengambil nilai baris ke 1 kolom ke 2 pada elemen array a
b[1,2]

## Slicing

### Select items at index 0 and 1

In [ ]:
# Mengambil nilai index ke 0 - 1 pada elemen array a
a[0:2]

### Select items at rows 0 and 1 in column 1

In [ ]:
# Mengambil nilai index ke 0 - 1 kolom ke 1 pada elemen array b
b[0:2,1] 

### Select all items at row 0 (equivalent to b[0:1, :])

In [ ]:
# Mengambil semua nilai baris ke 0 pada elemen array b
b[:1]

### Same as [1,:,:]

In [ ]:
# Mengambil semua nilai baris ke 1 pada elemen array c
c[1,...]

### Reversed array a 

In [ ]:
# Mengambil nilai pada elemen array a secara terbalik
a[ : :-1]

# Array Manipulation

## Transposing Array

### Permute array dimensions

In [ ]:
# Transpose array b
i = np.transpose(b)

In [ ]:
i.T

##  Changing Array Shape

### Flatten the array

In [ ]:
b

In [ ]:
# Meratakan array b menjadi satu dimensi
b.ravel()

### Reshape, but don’t change data

In [ ]:
g

In [ ]:
# Mengubah array g menjadi 2 dimensi
g.reshape(3,-2)

## Adding/Removing Elements

### Return a new array with shape (2,6) 

In [ ]:
h

In [ ]:
# Menambah jumlah elemen array
np.resize(h, (2,6))

### Append items to an array

In [ ]:
h

In [ ]:
g

In [ ]:
# Menambahkan elemen array h dengan array g 
np.append(h,g)

### Insert items in an array

In [ ]:
a

In [ ]:
# Memasukkan nilai 5 index ke 1 dalam array a
np.insert(a, 1, 5)

### Delete items from an array

In [ ]:
a

In [ ]:
# Menghapus elemen array a index ke 1
np.delete(a,[1])

## Combining Arrays

###  Concatenate arrays

In [ ]:
a

In [ ]:
d

In [ ]:
# Menggabungkan elemen array a dan d
np.concatenate((a,d),axis=0) 

### Stack arrays vertically (row-wise)

In [ ]:
a

In [ ]:
b

In [ ]:
# Susunan array secara vertikal (berdasarkan baris) array a dan b
np.vstack((a,b))

### Stack arrays vertically (row-wise)

In [ ]:
e

In [ ]:
f

In [ ]:
# Susunan array secara vertikal (berdasarkan baris) array e dan f
np.r_[e,f]

### Stack arrays horizontally (column-wise)

In [ ]:
# Susunan array secara horizontal (berdasarkan kolom) array e dan f
np.hstack((e,f))

### Create stacked column-wise arrays 

In [ ]:
a

In [ ]:
d

In [ ]:
# Susunan berdasarkan kolom array a dan d
np.column_stack((a,d))

### Create stacked column-wise arrays

In [ ]:
# Susunan berdasarkan kolom array a dan d
np.c_[a,d]

## Splitting Arrays

### Split the array horizontally at the 3rd index

In [ ]:
# Memisahkan array a secara horizontal pada indeks ke-3
np.hsplit(a,3)

### Split the array vertically at the 2nd index

In [ ]:
# Memisahkan array c secara vertikal pada indeks ke-2
np.vsplit(c,2)

# Thank You